#This file is generated by VisualGDB.
#It contains GCC settings automatically derived from the board support package (BSP).
#DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN. 
#Use VisualGDB Project Properties dialog or modify Makefile or per-configuration .mak files instead.

INCLUDE_DIRS += TestFramework/include TestFramework TestFramework/Platforms
PREPROCESSOR_MACROS += 
LIBRARY_NAMES += pthread
